
###
POST http://localhost:3001/api/user
Content-Type: application/json

{
    "username":"abolfo",
    "correo":"correo@hotmail.com"
    
}

###
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
   "username": "abolfo",
    "nombre": "Abolfo2",
    "correo": "correo@hotmail.com",
    "password": "abolfo12345",
    "profilePicture": "",
    "coverPicture": "",
    "desc": "",
    "city": "",
    "from": ""
}

###
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
   "username": "osita",
    "nombre": "Abolfo2",
    "correo": "correoe@hotmail.com",
    "password": "osita12345",
    "profilePicture": "",
    "coverPicture": "",
    "desc": "",
    "city": "",
    "from": ""
}


###
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
   "username": "sally",
    "nombre": "sally",
    "correo": "correoa@hotmail.com",
    "password": "sally12345"
}
//login
###
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
   
   "username": "abolfo",
    "password": "abolfo12345"
}

###
GET  http://localhost:3001/api/user

###
GET  http://localhost:3001/api/user/644705ba9ebd4916bd877c9a



###
PUT http://localhost:3001/api/user/641b8dc06f4a1fca0627f077
Content-Type: application/json

{
    "nombre":"abolfoo",
    "correo":"correo@hotmail.com"
}

###
DELETE   http://localhost:3001/api/user/641ba24ecbb0078646730ff1


//conversaciones

###
POST http://localhost:3001/api/conversations
Content-Type: application/json

{
    "senderId":"6449d135de539b7e7051e34a",
    "receiverId":"6449d07bde539b7e7051e33b"
}

###
POST http://localhost:3001/api/conversations/group
Content-Type: application/json

{
  "members": ["6449d09ade539b7e7051e33e", "6449d0b5de539b7e7051e341", "6449d0dede539b7e7051e344", "6449d0f7de539b7e7051e347", "6449d135de539b7e7051e34a"],
  "subgroup": "POI"
}

###
GET http://localhost:3001/api/conversations/6445b1c1d42fc9cebeae9259

//mensajes

###
POST http://localhost:3001/api/messages
Content-Type: application/json

{
    "conversationId":"644709dd181bf2845a2f63c4",
    "sender":"644705ba9ebd4916bd877c9a",
    "text":"el proyecto"
}
###
GET http://localhost:3001/api/messages/644709dd181bf2845a2f63c4



